name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1' 

    - name: Install dependencies
      run: npm install

    - name: Create .env file
      run: |
        echo "DATABASE_PATH=./config/mi_base_de_datos.sqlite" >> .env
        echo "JWT_SECRET=1234567890@@@@@1234567890!@#$%^&*()" >> .env
        echo "NODE_ENV=development" >> .env
        echo "TEST_DATABASE_PATH=:memory:" >> .env

    - name: Run tests
      run: npm test

    - name: Deploy to Render
      if: success() 
      env:
        RENDER_API_KEY: ${{ secrets.MYRENDER }} 
        RENDER_SERVICE_ID: somoslosmejores
      run: |
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
